tools:
  php_sim:
    min_mass: 30 # Defaults to 16

build:
  environment:
    php: 7.1
  dependencies:
    # Overwrites inferred commands
    override:
      - "composer install --no-interaction --ignore-platform-reqs --no-progress"
  tests:
    before:
      - "vendor/bin/phpcs src/"
      - "vendor/bin/phpcs tests/"
      - "vendor/bin/phpunit"

checks:
  php: true